---
title: codemelted.js Object Enumerations
---
classDiagram
  direction BT
  note "<b>DESCRIPTION:<b> Enumerations provide support for the<br>public API functions and supporting objects.<br><b>SUPPORTED RUNTIMES:<b> all"

  class ACTION_REQUEST {
    + Alert: "alert",
    + Confirm: "confirm",
    + Focus: "focus",
    + MoveBy: "move_by",
    + MoveTo: "move_to",
    + PostMessage: "post_message",
    + Print: "print",
    + Prompt: "prompt",
    + ResizeBy: "resize_by",
    + ResizeTo: "resize_to",
    + Scroll: "scroll",
    + ScrollBy: "scroll_by",
    + ScrollTo: "scroll_to",
    + Share: "share",
    + Vibrate: "vibrate",
  }
  ACTION_REQUEST --|> object: implements

  class AUDIO_REQUEST {
    AudioPlayer: "audio_player"
    TextToSpeech: "text_to_speech"
  }
  AUDIO_REQUEST --|> object: implements

  class CONNECT_REQUEST {
    + BroadcastChannel: "broadcast_channel"
    + EventSource: "event_source"
    + WebSocket: "web_socket"
    + WebRTC: "web_rtc"
  }
  CONNECT_REQUEST --|> object: implements

  class DEFINED_REQUEST {
    + AskRuntime: "ask_runtime"
    + Audio: "audio"
    + Browser: "browser"
    + Bun: "bun"
    + Bluetooth: "bluetooth"
    + Deno: "deno"
    + MIDI: "midi"
    + Node: "node"
    + Orientation: "orientation"
    + PWA: "pwa"
    + SerialPort: "serial_port"
    + SecureContext: "secure_context"
    + Share: "share"
    + TextToSpeech: "text_to_speech"
    + TouchEnabled: "touch_enabled"
    + USB: "usb"
    + WorkerAvailable: "worker_available"
    + WorkerRuntime: "worker_runtime"
  }
  DEFINED_REQUEST --|> object: implements

  class EVENT_REQUEST {
    + Add: "add"
    + Remove: "remove"
  }
  EVENT_REQUEST --|> object: implements

  class LOGGER_REQUEST {
    + Debug: object
    + Info: object
    + Warning: object
    + Error: object
    + Off: object
  }
  note for LOGGER_REQUEST "object comprises 'level' / 'label' properties"
  LOGGER_REQUEST --|> object: implements

  class PROTOCOL_EVENT {
    + Error: "error"
    + Message: "message"
    + MessageError: "message_error"
    + Open: "open"
    + Started: "started"
    + Terminated: "terminated"
  }
  PROTOCOL_EVENT --|> object: implements

  class PROTOCOL_TYPE {
    + Audio: "audio"
    + Bluetooth: "ble"
    + BroadcastChannel: "broadcast_channel"
    + EventSource: "event_source"
    + GamePad: "game_pad"
    + Midi: "midi"
    + Orientation: "orientation"
    + SerialPort: "serial_port"
    + Timer: "timer"
    + Usb: "usb"
    + WebRTC: "web_rtc"
    + WebSocket: "web_socket"
    + Worker: "worker"
  }
  PROTOCOL_TYPE --|> object: implements

  class SCREEN_REQUEST {
    + AvailableHeight: "available_height",
    + AvailableWidth: "available_width",
    + ColorDepth: "color_depth",
    + DevicePixelRatio: "device_pixel_ratio",
    + Height: "height",
    + InnerHeight: "inner_height",
    + InnerWidth: "inner_width",
    + OuterHeight: "outer_height",
    + OuterWidth: "outer_width",
    + PixelDepth: "pixel_depth",
    + ScreenLeft: "screen_left",
    + ScreenOrientationAngle: "screen_orientation_angle",
    + ScreenOrientationType: "screen_orientation_type",
    + ScreenTop: "screen_top",
    + ScreenX: "screen_x",
    + ScreenY: "screen_y",
    + ScrollX: "scroll_x",
    + ScrollY: "scroll_y",
    + Width: "width",
  }
  SCREEN_REQUEST --|> object: implements

  class SCHEMA_TYPE {
    + File: "file:"
    + Http: "http://"
    + Https: "https://"
    + Mailto: "mailto:"
    + Sms: "sms:"
    + Tel: "tel:"
  }
  SCHEMA_TYPE --|> object: implements

  class SERIAL_PORT_DATA_REQUEST {
    + Break: "break"
    + CarrierDetect: "carrier_detect"
    + ClearToSend: "clear_to_send"
    + DataBytesRead: "data_bytes_read"
    + DataBytesWrite: "data_bytes_write"
    + DataSetReady: "data_set_ready"
    + DataTerminalReady: "data_terminal_ready"
    + RequestToSend: "request_to_send"
    + RingIndicator: "ring_indicator"
  }
  SERIAL_PORT_DATA_REQUEST --|> object: implements

  class STORAGE_TYPE {
    + Cookie: "cookie"
    + Local: "local"
    + Session: "session"
  }
  STORAGE_TYPE --|> object: implements

  class TARGET_TYPE {
    + Blank: "_blank"
    + Parent: "_parent"
    + Self: "_self"
    + Top: "_top",
  }
  TARGET_TYPE --|> object: implements
